version: "3"

services:
  app:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./db:/app/db
    environment:
      FLASK_APP: app
    entrypoint:
      - "sh"
      - "entrypoint.sh"
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
    depends_on:
      - pg

  pg:
    image: postgres:12.3
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1m"
    ports:
      - 5432:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres